spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: root
    name: system
  sql:
    init:
      mode: always
spring.jpa:
  hibernate.ddl-auto: none
  defer-datasource-initialization: true